core: Fix class loader issue in WildFly 10
WildFly 10 extracted javax.sql API into its own module, which caused
following exception when executing ovirt-aaa-jdbc-tool:

  IllegalArgumentException: javax.sql.DataSource is not visible from
  class loader

To fix that we need to use this.getClass().getClassLoader() instead of
Thread.currentThread().getContextClassLoader() to create DataSource
proxy.

Change-Id: Ia0ffcb01f26f3389ad62574fc450313c7a6d54b7
Signed-off-by: Martin Perina <mperina@redhat.com>